version: 2.1

jobs:

  build-docs:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Install CI dependencies
          command: python -m pip install --upgrade tox

      - run:
          name: Build HTML rendering of notebooks
          no_output_timeout: 30m
          command: |
            python -m tox -e py311-buildhtml

      - store_artifacts:
          path: _build/html

workflows:
  version: 2
  default:
    jobs:
      - build-docs
